import os

#dirs = list(filter(lambda x: os.path.isdir(x), os.listdir(os.path.dirname(os.path.abspath(__file__)))))
abs_path = os.path.abspath(__file__)
print(abs_path)
file_dir = os.path.dirname(abs_path)
print(file_dir)
dirs = os.listdir(file_dir)
print(dirs)
ds = os.listdir(os.path.dirname(os.path.abspath(__file__)))
print(ds)
dds = list(filter(lambda x: os.path.isdir(x), os.listdir(os.path.dirname(os.path.abspath(__file__)))))
print(dds)
new_dirs = list(filter(lambda x: len(x) <= 8, dds))
new_dirs.remove('logs')
print(new_dirs)
