# Generated by Django 2.2.5 on 2020-01-09 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='登录名')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户是否激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='账户是否后台管理员')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_first_class', models.CharField(max_length=20, verbose_name='商品一类')),
            ],
            options={
                'verbose_name_plural': '商品一类',
            },
        ),
        migrations.CreateModel(
            name='GoodsSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_specs', models.CharField(max_length=20, verbose_name='商品规格')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
            ],
            options={
                'verbose_name_plural': '商品规格',
            },
        ),
        migrations.CreateModel(
            name='GoodsThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('goods_introduction', models.CharField(max_length=255, verbose_name='商品简介')),
                ('goods_detail', models.CharField(max_length=255, verbose_name='商品详情')),
            ],
            options={
                'verbose_name_plural': '商品三类',
            },
        ),
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='轮播图片')),
                ('number', models.IntegerField(verbose_name='序号')),
            ],
            options={
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(max_length=20, verbose_name='收件人')),
                ('addressee_phone', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('address', models.CharField(max_length=255, verbose_name='收件地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认收货地址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单地址',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_text', models.TextField(verbose_name='五谷小知识')),
                ('tips_img', models.ImageField(upload_to='', verbose_name='五谷小知识配图')),
            ],
            options={
                'verbose_name_plural': '五谷小知识',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=20, verbose_name='用户偏好')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='ReceiveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=255, verbose_name='收件地址')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收件信息',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='订单编号')),
                ('pay_ways', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信'), (3, '银联')], default=1, verbose_name='支付方式')),
                ('carriage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='运费')),
                ('express', models.SmallIntegerField(choices=[(1, '普通快递(包邮)'), (2, '顺丰'), (3, 'EMS')], default=1, verbose_name='快递方式')),
                ('sum_goods', models.IntegerField(verbose_name='商品总数')),
                ('sum_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品总价')),
                ('payment_status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '退款中'), (3, '已退款')], verbose_name='支付状态')),
                ('order_generation_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.OrderAddress', verbose_name='地址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_quantity', models.IntegerField(verbose_name='商品数量')),
                ('goods_sum_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='商品')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.OrderInfo', verbose_name='订单')),
            ],
            options={
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.AddField(
            model_name='goodsspecs',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='商品'),
        ),
        migrations.CreateModel(
            name='GoodsSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_second_class', models.CharField(max_length=20, verbose_name='商品二类')),
                ('goods_first_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsFirst', verbose_name='商品一类')),
                ('goods_third_class', models.ManyToManyField(to='wugu.GoodsThird', verbose_name='商品三类')),
            ],
            options={
                'verbose_name_plural': '商品二类',
            },
        ),
        migrations.CreateModel(
            name='GoodsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_img', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='GoodsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='商品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='DiscountGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='折扣价')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '打折商品',
            },
        ),
        migrations.CreateModel(
            name='ComposedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composed_goods_description', models.CharField(max_length=255, verbose_name='组合商品描述')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='优惠价格')),
                ('goods_specs', models.ManyToManyField(to='wugu.GoodsSpecs', verbose_name='规格')),
            ],
            options={
                'verbose_name_plural': '组合商品',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_detail', models.CharField(max_length=255, verbose_name='详细评价')),
                ('star', models.SmallIntegerField(choices=[(1, '非常不满意'), (2, '不满意'), (3, '一般'), (4, '满意'), (5, '非常满意')], verbose_name='星级')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('goods_specs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='规格')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评价',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('cart_generation_time', models.DateTimeField(auto_now_add=True, verbose_name='购物车创建时间')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='商品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
            },
        ),
    ]
