# Generated by Django 2.2.5 on 2020-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像'),
        ),
    ]
