# Generated by Django 2.2.5 on 2020-01-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0002_userinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsthird',
            name='goods_introduction',
        ),
        migrations.AddField(
            model_name='goodsimages',
            name='goods_img_detail',
            field=models.ImageField(default=0, upload_to='', verbose_name='商品详情图'),
        ),
        migrations.AddField(
            model_name='goodsspecs',
            name='goods_introduction',
            field=models.CharField(max_length=255, null=True, verbose_name='商品简介'),
        ),
        migrations.AddField(
            model_name='goodsspecs',
            name='goods_title',
            field=models.CharField(max_length=20, null=True, verbose_name='商品标题'),
        ),
        migrations.AlterField(
            model_name='goodsimages',
            name='goods_img',
            field=models.ImageField(upload_to='', verbose_name='商品展示图'),
        ),
        migrations.AlterField(
            model_name='goodsspecs',
            name='goods_price',
            field=models.CharField(max_length=20, verbose_name='商品价格'),
        ),
    ]
