# Generated by Django 2.2.5 on 2020-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0003_auto_20200109_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_generation_time',
            field=models.DateTimeField(auto_now_add=True, max_length=19, verbose_name='购物车创建时间'),
        ),
    ]
