# Generated by Django 2.2.5 on 2020-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0005_auto_20200110_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountgoods',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='折扣价'),
        ),
    ]
