# Generated by Django 2.2.5 on 2020-01-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0006_auto_20200110_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.SmallIntegerField(choices=[(1, '普通快递(包邮)'), (2, '顺丰'), (3, 'EMS')], default=1, verbose_name='快递方式')),
                ('carriage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='运费')),
            ],
        ),
        migrations.AlterField(
            model_name='goodsimages',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='三类商品'),
        ),
        migrations.AlterField(
            model_name='goodsspecs',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='三类商品'),
        ),
    ]
