# Generated by Django 2.2.5 on 2020-01-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0007_auto_20200111_0139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postage',
            new_name='Carriage',
        ),
        migrations.AlterModelOptions(
            name='carriage',
            options={'verbose_name_plural': '邮费'},
        ),
    ]
