# Generated by Django 2.2.5 on 2020-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0008_auto_20200111_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsspecs',
            name='goods_sale',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
    ]
