# Generated by Django 2.2.5 on 2020-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0009_goodsspecs_goods_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspecs',
            name='goods_introduction',
            field=models.CharField(default='纯天然，无公害', max_length=255, verbose_name='商品简介'),
        ),
    ]
