# Generated by Django 2.2.5 on 2020-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0010_auto_20200111_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_s1', models.ImageField(upload_to='', verbose_name='小图1')),
                ('img_b1', models.ImageField(upload_to='', verbose_name='大图1')),
                ('img_s2', models.ImageField(upload_to='', verbose_name='小图2')),
                ('img_b2', models.ImageField(upload_to='', verbose_name='大图2')),
                ('img_s3', models.ImageField(upload_to='', verbose_name='小图3')),
                ('img_b3', models.ImageField(upload_to='', verbose_name='大图3')),
                ('img_s4', models.ImageField(upload_to='', verbose_name='小图4')),
                ('img_b4', models.ImageField(upload_to='', verbose_name='大图4')),
                ('img_d1', models.ImageField(upload_to='', verbose_name='详情图1')),
                ('img_d2', models.ImageField(upload_to='', verbose_name='详情图2')),
                ('img_d3', models.ImageField(upload_to='', verbose_name='详情图3')),
            ],
        ),
    ]
