# Generated by Django 2.2.5 on 2020-01-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0012_goodsdetailimages_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetailimages',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='三类商品'),
        ),
    ]
