# Generated by Django 2.2.5 on 2020-01-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0013_auto_20200111_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsdetailimages',
            options={'verbose_name_plural': '商品详情图'},
        ),
        migrations.AlterField(
            model_name='goodsdetailimages',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsSpecs', verbose_name='商品'),
        ),
        migrations.CreateModel(
            name='GoodsThirdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_show', models.ImageField(upload_to='', verbose_name='商品展示图')),
                ('img_detail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品详情图')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='三类商品')),
            ],
            options={
                'verbose_name_plural': '商品主、副图',
            },
        ),
    ]
