# Generated by Django 2.2.5 on 2020-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0014_auto_20200111_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsthirdimages',
            name='img_recommend',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='推荐商品图'),
        ),
    ]
