# Generated by Django 2.2.5 on 2020-01-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0015_goodsthirdimages_img_recommend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsthirdimages',
            options={'verbose_name_plural': '商品三类副图'},
        ),
        migrations.RemoveField(
            model_name='goodsthirdimages',
            name='img_recommend',
        ),
    ]
