# Generated by Django 2.2.5 on 2020-01-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0016_auto_20200111_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsthirdimages',
            options={'verbose_name_plural': '商品三类展示图'},
        ),
        migrations.CreateModel(
            name='GoodsThirdDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_detail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品详情图')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.GoodsThird', verbose_name='三类商品')),
            ],
            options={
                'verbose_name_plural': '商品三类详情图',
            },
        ),
    ]
