# Generated by Django 2.2.5 on 2020-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0017_auto_20200111_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsthirddetailimages',
            options={'verbose_name_plural': '商三详情图'},
        ),
        migrations.AlterModelOptions(
            name='goodsthirdimages',
            options={'verbose_name_plural': '商三展示图'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='用户头像'),
        ),
    ]
