# Generated by Django 2.2.5 on 2020-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0018_auto_20200112_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=2, null=True, verbose_name='性别'),
        ),
    ]
