# Generated by Django 2.2.5 on 2020-01-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0020_ordergoods_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_number',
            field=models.BigIntegerField(verbose_name='订单编号'),
        ),
    ]
