# Generated by Django 2.2.5 on 2020-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0021_auto_20200112_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='carriage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='payment_status',
            field=models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '退款中'), (3, '已退款')], default=1, verbose_name='支付状态'),
        ),
    ]
