# Generated by Django 2.2.5 on 2020-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0022_auto_20200112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='sum_goods',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品总数'),
        ),
    ]
