# Generated by Django 2.2.5 on 2020-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0023_auto_20200112_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='goods_sum_price',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='sum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='商品总价'),
        ),
    ]
