# Generated by Django 2.2.5 on 2020-01-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0024_auto_20200112_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposedGoodsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_composed', models.ImageField(upload_to='', verbose_name='组合商品图')),
            ],
        ),
        migrations.RemoveField(
            model_name='composedgoods',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='composedgoods',
            name='goods_specs',
        ),
        migrations.AddField(
            model_name='composedgoods',
            name='composed_goods_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组合商品名称'),
        ),
        migrations.AddField(
            model_name='composedgoods',
            name='new_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='现价'),
        ),
        migrations.AddField(
            model_name='composedgoods',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='goodsimages',
            name='goods_img',
            field=models.ImageField(upload_to='', verbose_name='商品主图'),
        ),
    ]
