# Generated by Django 2.2.5 on 2020-01-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0025_auto_20200113_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composedgoodsimages',
            options={'verbose_name_plural': '组合商品图'},
        ),
        migrations.AddField(
            model_name='composedgoodsimages',
            name='composed_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wugu.ComposedGoods', verbose_name='组合商品'),
        ),
    ]
