# Generated by Django 2.2.5 on 2020-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wugu', '0026_auto_20200113_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='composedgoods',
            name='composed_goods_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组合商品详情'),
        ),
    ]
