# Generated by Django 3.1 on 2020-08-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True, verbose_name='组名')),
                ('home_page', models.CharField(blank=True, max_length=128, null=True, verbose_name='首页')),
                ('app_detail_page', models.CharField(blank=True, max_length=128, null=True, verbose_name='详情页')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮件')),
                ('etherpad', models.CharField(blank=True, max_length=255, null=True, verbose_name='etherpad')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='组描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=128, null=True, verbose_name='昵称')),
                ('gitee_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='gitee名称')),
                ('avatar', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户头像')),
                ('gender', models.CharField(blank=True, choices=[(0, '女'), (1, '男')], max_length=6, null=True, verbose_name='性别')),
                ('openid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='openid')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='unionid')),
                ('status', models.SmallIntegerField(choices=[(0, '未登陆'), (1, '登陆')], default=0, verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(1, '普通用户'), (2, '授权用户'), (3, '管理员')], default=1, verbose_name='权限级别')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个性签名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='最近登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='会议主题')),
                ('date', models.CharField(max_length=30, verbose_name='会议日期')),
                ('start_time', models.CharField(max_length=30, verbose_name='会议开始时间')),
                ('end_time', models.CharField(max_length=30, verbose_name='会议结束时间')),
                ('agenda', models.TextField(blank=True, default='', null=True, verbose_name='议程')),
                ('etherpad', models.CharField(blank=True, max_length=255, null=True, verbose_name='etherpad')),
                ('emaillist', models.TextField(blank=True, null=True, verbose_name='邮件列表')),
                ('host_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='host_id')),
                ('meeting_id', models.CharField(max_length=20, verbose_name='会议id')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='时区')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='会议密码')),
                ('start_url', models.TextField(blank=True, null=True, verbose_name='开启会议url')),
                ('join_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='进入会议url')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.group', verbose_name='SIG组')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='meetings.User'),
        ),
    ]
