# Generated by Django 3.1 on 2020-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwdopenid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='pwdopenid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], max_length=6, null=True, verbose_name='性别'),
        ),
    ]
