# Generated by Django 3.1 on 2020-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200818_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='电话')),
                ('username', models.CharField(blank=True, max_length=10, unique=True, verbose_name='账户')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='名字')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_img/', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户是否激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='账户是否后台管理员')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
