# Generated by Django 3.1 on 2020-08-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='openid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
