# Generated by Django 3.1 on 2020-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20200818_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group_id', 'user_id')},
        ),
    ]
