# Generated by Django 2.2.5 on 2020-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupitem',
            name='host_email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='组主持人邮箱'),
        ),
        migrations.AlterField(
            model_name='groupitem',
            name='host_logo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主持人头像logo'),
        ),
        migrations.AlterField(
            model_name='groupitem',
            name='host_wechat_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主持人微信id'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='agenda',
            field=models.TextField(blank=True, null=True, verbose_name='议程'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='group_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='join_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='进入会议url'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会议id'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='会议密码'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='start_url',
            field=models.TextField(blank=True, null=True, verbose_name='开启会议url'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '紧急会议'), (2, '预定会议')], null=True, verbose_name='会议类型'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='zoom_host',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='主持人邮箱'),
        ),
    ]
