# Generated by Django 2.2.5 on 2020-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200804_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '预定会议'), (1, '紧急会议')], default=2, verbose_name='会议类型'),
        ),
    ]
