# Generated by Django 2.2.5 on 2020-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200804_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupitem',
            name='group_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='组名'),
        ),
        migrations.AlterField(
            model_name='loginitem',
            name='wechat_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='微信id'),
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '预定会议'), (1, '紧急会议')], default=2, null=True, verbose_name='会议类型'),
        ),
    ]
